### ISSUE TITLE
Usage example? 

### ISSUE THREAD

**Issue by gdubya** [realityforge/gwt-keycloak#1]
Hi, we have a legacy gwt project that we would like to integrate with a keycloak server. Could you provide an example usage of this adapter that we can learn from?

**Comment by gdubya** [comment]
Sorry, you already did that. I'll look more closely at it. The question should have been: how can we get the keycloak.json if it's not a public resource? Is it possible to read it from the classpath?

**Comment by realityforge** [comment]
As it stands, `gwt-keycloak` just uses the underlying javascript API which accepts a url. It may be possible to use a [data uri](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) to encode the `keycloak.json` file although I have not checked if that works.

The other alternative is some minor changes to `gwt-keycloak` that offers another constructor where a javascript literal is passed in which I believe is supported by the underlying keycloak.js library.

I don't have time to implement this atm but will happily accept a pull request ;)

**Comment by assadriaz** [comment]
I have tested data uri and it works , thanks :)

**Comment by isko04** [comment]
Hi, first of all thanks for the nice project. I integrated it in our gwt-project and token generation works fine after login. But when I do a REST-service call using the token I always get the following error. I use the keycloak Java Servlet Adapter to protect the REST-services. In keycloak.json cors is enabled and WebOrigins is set to *.

Access to XMLHttpRequest at 'http://localhost:8180/auth/realms/configdb/protocol/openid-connect/auth?response_type=code&client_id=configdb-frontend&redirect_uri=http%3A%2F%2F127.0.0.1%3A8888%2FConfigDB%2Fapi%2Fdirectory%2Flogin&state=4b976bf8-1dae-4eeb-91c2-49691754a85c&login=true&scope=openid' (redirected from 'http://127.0.0.1:8888/ConfigDB/api/directory/login') from origin 'http://127.0.0.1:8888' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Maybe my question doesn't concern gwt-keycloak directly, but I haven't found a solotion for days and perhaps you have encountered similar problems in your gwt project an know what to do. 
I'm testing in gwt development mode.
Thanks a lot!

**Comment by realityforge** [comment]
It is difficult to guess at what the problem is but this seems more likely related to CORS setup rather than anything keycloak and/or gwt specific. 

I suspect you are not setting with `withCredentials` on the XMLHttpRequests. See https://www.html5rocks.com/en/tutorials/cors/#toc-withcredentials for a basic overview on how to do this in javascript which should get you started in whatever framework you are using.

Otherwise, just have a read through [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) docs and try and spot what HTTP headers you are missing ;)

Good luck!

**Comment by aamir9138** [comment]
I am running keycloak on dockers. and I really don't know what this URL to keycloak.json means.

can you please describe the line

final Keycloak keycloak = new Keycloak( "MyApp", "http://127.0.0.1:8080/myapp/keycloak.json" );

I think here

"MyApp" == realm
"myapp" == clientId

but I am not sure. please if anyone can guide me. I want to use keycloak with GWT
