### ISSUE TITLE
$wnd.Keycloak undefined when instantiating Keycloak

### ISSUE THREAD

**Issue by cp-cheung** [realityforge/gwt-keycloak#2]
Environment: Windows 10, GWT 2,8.2

Relevant code or config:
```
Keycloak keycloak = new Keycloak("MyApp", "a working url");
```

What you did:

Started the application

What happened:
When staring the application, the following message appears in the browser console log:

Uncaught TypeError: $wnd.Keycloak is not a function
    at i$n_g$ (Keycloak.java:393)
    at new SYn_g$ (Keycloak.java:45)
    at MLl_g$.NLl_g$ [as onModuleLoad_0_g$] (MyApp.java:28)
    at Array.hef_g$ 

Reproduction repository:

Problem description:

Suggested solution:

**Comment by realityforge** [comment]
The `gwt-keycloak` code does not provide the keycloak javascript but instead just provides a gwt-ish wrapper around keycloak javascript. Typically you need to include this javascript in the page before the script tag that loads the gwt app. This is done via something like

```html
<script src="http://myauthserver.com/auth/js/keycloak.min.js"></script>
```

HTH
